#! /bin/sh

### BEGIN INIT INFO
# Provides:        tsvms
# Required-Start:  $network $remote_fs
# Required-Stop:   $network $remote_fs
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start TS VMS (Vibration Monitor System) daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/bin:/usr/sbin

DAEMON=/usr/sbin/tsvmsd
PIDFILE=/var/run/tsvmsd

# rcS contains TICKADJ
test -r /etc/default/rcS && . /etc/default/rcS

# Source function library.
. /etc/init.d/functions

# Source devices
. /etc/default/tsvmsd

startdaemon(){
	echo -n "Starting TS VMS $1:"
	start-stop-daemon --start --oknodo --pidfile ${PIDFILE}_$1.pid --startas $DAEMON -- -p ${PIDFILE}_$1.pid -u vms:vms -c $1
	echo "done"
}
stopdaemon(){
	echo -n "Stopping TS VMS $1:"
	start-stop-daemon --stop --retry 5 -p ${PIDFILE}_$1.pid
	echo "done"
}
startall(){
	for v in $VMS; do
		startdaemon $v
	done
}
stopall(){
	for v in $VMS; do
		stopdaemon $v
	done
}

case "$1" in
  start)
	startall
	;;
  stop)
  	stopall
	;;
  restart)
	stopll
	startall
	;;
  status)
	status /usr/sbin/ts_MTVMS;
	exit $?
	;;
  *)
	echo "Usage: tsvms { start | stop | status | restart }" >&2
	exit 1
	;;
esac

exit 0
