#! /bin/sh

### BEGIN INIT INFO
# Provides:        tsvms
# Required-Start:  $network $remote_fs
# Required-Stop:   $network $remote_fs
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start TS VMS (Vibration Monitor System) daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/bin:/usr/sbin

DAEMON=/usr/sbin/ts_MTVMS
PIDFILE=/var/run/tsvms.pid

# rcS contains TICKADJ
test -r /etc/default/rcS && . /etc/default/rcS

# Source function library.
. /etc/init.d/functions

startdaemon(){
	echo -n "Starting TS VMS: "
	start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- -p $PIDFILE -u vms:vms -c M1M3
	echo "done"
}
stopdaemon(){
	echo -n "Stopping TS VMS: "
	start-stop-daemon --stop --quiet --oknodo -p $PIDFILE
	echo "done"
}

case "$1" in
  start)
	startdaemon -g
	;;
  stop)
  	stopdaemon
	;;
  restart)
	stopdaemon
	startdaemon
	;;
  status)
	status /usr/sbin/ts_MTVMS;
	exit $?
	;;
  *)
	echo "Usage: tsvms { start | stop | status | restart }" >&2
	exit 1
	;;
esac

exit 0
